version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
  docker: circleci/docker@2.1.3

jobs:
  build:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      - run: |
          echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
          docker run -d --name db company/proprietary-db:1.2.3

      # build the application image
      - run: docker build -t $DOCKER_LOGIN/joke-api:$CIRCLE_BRANCH .

      # deploy the image
      - run: docker push $DOCKER_LOGIN/joke-api:$CIRCLE_BRANC

workflows:
  build:
    jobs:
      - node/run:
          npm-run: build
          filters:
            branches:
              only:
                - main
      - node/test:
          requires:
            - "node/run"
          filters:
            branches:
              only:
                - main
      - heroku/deploy-via-git:
          requires:
            - node/run
            - node/test
          app-name: "joke-app-iw4"
          filters:
            branches:
              only:
                - main
      - docker/publish:
          image: tufengs/joke-app:latest
          requires:
            - node/run
            - node/test
          filters:
            branches:
              only:
                -main