version: 2.1

orbs:
  node: circleci/node@5.0.2

workflows:
  build:
    jobs:
      - node/run:
          npm-run: build
          filters:
            branches:
              only:
                - main
      - node/test:
          test-result-for: jest
          filters:
            branches:
              only:
                - main